### ISSUE TITLE
Uncaught TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by sbozzie** [dan12mol/toggl#2]
1. With no currently active toggl entry running
2. using command console, activate Toggl:End
3. observe error message

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [toggl](https://github.com/dan12mol/toggl) package, v0.6.0
### Stack Trace

Uncaught TypeError: Cannot read property 'statusCode' of undefined

```
At C:\Users\Samuel\.atom\packages\toggl\node_modules\toggl-api\lib\client.js:211

TypeError: Cannot read property 'statusCode' of undefined
  at Request.onresponse [as _callback] (C:\Users\Samuel\.atom\packages\toggl\node_modules\toggl-api\lib\client.js:211:30)
  at self.callback (C:\Users\Samuel\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\request\request.js:123:22)
  at emitOne (events.js:77:13)
  at Request.emit (events.js:166:7)
  at ClientRequest.self.clientErrorHandler (C:\Users\Samuel\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\request\request.js:244:10)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketErrorListener (_http_client.js:254:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at net.js:438:14
  at process._tickCallback (node.js:357:13)

```
### Commands

```
  2x -3:10.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:09.7.0 core:save (atom-text-editor.editor.is-focused)
     -2:14.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:12.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:25.1.0 core:paste (atom-text-editor#toggl.togglApiKey.editor.mini.is-focused)
     -1:11.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:58.4.0 application:run-all-specs (table.package-keymap-table.table.native-key-bindings.text)
     -0:51.6.0 core:save-as (table.package-keymap-table.table.native-key-bindings.text)
     -0:40.9.0 core:save (table.package-keymap-table.table.native-key-bindings.text)
     -0:36.8.0 command-palette:toggle (table.package-keymap-table.table.native-key-bindings.text)
     -0:33.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:27.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.4.0 Toggl:Start (table.package-keymap-table.table.native-key-bindings.text)
     -0:14.9.0 command-palette:toggle (div.settings-view.pane-item)
     -0:07.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.9.0 Toggl:End (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {
    "themes": [
      "isotope-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "wrap-guide"
    ],
    "projectHome": "D:\\Atom Projects"
  },
  "toggl": {
    "togglApiKey": "TOGG API KEY HERE"
  }
}
```
### Installed Packages

``` coffee
# User
isotope-ui, v2.4.2
language-lsl, v2.0.3
minimap, v4.10.0
toggl, v0.6.0

# Dev
No dev packages
```

**Comment by datachand** [comment]
I am getting the same error, any mention on fixes
